spring.application.name=ticket-ai-system
server.port=8089

# Hugging Face config
huggingface.api.key=${HF_API_KEY}

huggingface.api.url=https://router.huggingface.co/v1/chat/completions
huggingface.model=openai/gpt-oss-120b:fastest